name: "Request reviews"
on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]

jobs:
  reviewers:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: uesteibar/reviewer-lottery@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
